export const PAGE_LOAD = "PAGE_LOAD";
export const PEOPLE_RESPONSE_RECEIVED = "PEOPLE_RESPONSE_RECEIVED";
export const PERSON_SELECTED = "PERSON_SELECTED";
export const CLEAR_FILMS = "CLEAR_FILMS"
export const FILM_LOADING = "FILM_LOADING"
export const FILM_RESPONSE_RECEIVED = "FILM_RESPONSE_RECEIVED"


